name: widgetbook_workspace
description: The widgetbook environment for ui_kit_library
publish_to: 'none'
environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  widgetbook: ^3.20.2
  widgetbook_annotation: ^3.9.0
  # Reference the outer UI Kit
  ui_kit_library:
    path: ../
dev_dependencies:
  build_runner: ^2.4.8
  widgetbook_generator: ^3.20.1
flutter:
  uses-material-design: true